name: smart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^5.1.0
  mask_text_input_formatter: ^2.4.0
  flutter_svg: ^2.0.7
  easy_localization: ^3.0.2
  cupertino_icons: ^1.0.2
  appwrite: ^9.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2
  loading_animations: ^2.2.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: 2.2.19

flutter_native_splash:
  color: "#ED5434"
  image: "Assets/splash.png"

flutter:
  uses-material-design: true
  assets:
    - Assets/
    - Assets/icons/

